# Generated by Django 4.0.1 on 2022-01-19 15:27

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('dateCreate', models.DateTimeField()),
                ('likeCount', models.IntegerField(null=True)),
                ('viewCount', models.IntegerField(null=True)),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('dateCreate', models.DateTimeField()),
                ('likeCount', models.IntegerField(null=True)),
                ('viewCount', models.IntegerField(null=True)),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
