# Generated by Django 4.0.1 on 2022-01-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_boardmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardMember',
        ),
    ]
