# Generated by Django 4.0.1 on 2022-01-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0003_delete_boardmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='dateCreate',
        ),
        migrations.RemoveField(
            model_name='postmajor',
            name='dateCreate',
        ),
        migrations.AddField(
            model_name='postjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='최종수정일'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.boardmember', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='postmajor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='postmajor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='최종수정일'),
        ),
        migrations.AddField(
            model_name='postmajor',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.boardmember', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='likeCount',
            field=models.IntegerField(null=True, verbose_name='좋아요수'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='viewCount',
            field=models.IntegerField(null=True, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='postmajor',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='postmajor',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='postmajor',
            name='likeCount',
            field=models.IntegerField(null=True, verbose_name='좋아요수'),
        ),
        migrations.AlterField(
            model_name='postmajor',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='postmajor',
            name='viewCount',
            field=models.IntegerField(null=True, verbose_name='조회수'),
        ),
    ]
