# Generated by Django 4.0.1 on 2022-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postjob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmajor',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='category'),
        ),
    ]
