# Generated by Django 4.0.1 on 2022-01-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0006_postmajor_name_alter_postjob_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('img', models.ImageField(upload_to='', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='최종수정일')),
                ('likeCount', models.IntegerField(null=True, verbose_name='좋아요수')),
                ('viewCount', models.IntegerField(null=True, verbose_name='조회수')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='게시판명')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.boardmember', verbose_name='작성자')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmajor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postmajor',
            name='writer',
        ),
        migrations.DeleteModel(
            name='PostJob',
        ),
        migrations.DeleteModel(
            name='PostMajor',
        ),
    ]
